// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RjWf8krvaQVQJrIRnemltD4pXimgPrE',
    appId: '1:404429072054:web:5ae8dae660e35189076817',
    messagingSenderId: '404429072054',
    projectId: 'readlevelproject-6e5d3',
    authDomain: 'readlevelproject-6e5d3.firebaseapp.com',
    storageBucket: 'readlevelproject-6e5d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYHe9gogXdKCZaduy4teQon_lxIrJf4U',
    appId: '1:404429072054:android:3d0aeb2baadc819f076817',
    messagingSenderId: '404429072054',
    projectId: 'readlevelproject-6e5d3',
    storageBucket: 'readlevelproject-6e5d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9yDVJA1BKRBxJk20SqyE2PQq1CSUf8c',
    appId: '1:404429072054:ios:edec416c19348bc2076817',
    messagingSenderId: '404429072054',
    projectId: 'readlevelproject-6e5d3',
    storageBucket: 'readlevelproject-6e5d3.firebasestorage.app',
    iosBundleId: 'com.example.miniRead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9yDVJA1BKRBxJk20SqyE2PQq1CSUf8c',
    appId: '1:404429072054:ios:edec416c19348bc2076817',
    messagingSenderId: '404429072054',
    projectId: 'readlevelproject-6e5d3',
    storageBucket: 'readlevelproject-6e5d3.firebasestorage.app',
    iosBundleId: 'com.example.miniRead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_RjWf8krvaQVQJrIRnemltD4pXimgPrE',
    appId: '1:404429072054:web:33337a33443edef5076817',
    messagingSenderId: '404429072054',
    projectId: 'readlevelproject-6e5d3',
    authDomain: 'readlevelproject-6e5d3.firebaseapp.com',
    storageBucket: 'readlevelproject-6e5d3.firebasestorage.app',
  );

}